name: Release_Pipeline_Windows
on:
  push:
    branches:
      - main
  schedule:
      - cron: '40 16 * * *'    
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy: 
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Chrome WebDriver
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          LATEST_CHROMEDRIVER_VERSION=$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d $HOME/bin

      - name: Execute Behave tests Windows
        if: matrix.os=='windows-latest' 
        run: 
          behave .\features\OrgangeHRMLogin.feature
      - name: Execute Behave tests Non Windows
        if: matrix.os=='ubuntu-latest'|| matrix.os== 'macos-latest'
        run: 
          behave ./features/OrgangeHRMLogin.feature    
      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: JunitReports/TESTS-*.xml
    
