name: Release_Pipeline_Windows
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r PIPELINE_TRAINNG_PROJECT/requirements.txt
      - name: Execute Behave tests
        run: |
          cd PIPELINE_TRAINNG_PROJECT
          behave .\features\OrgangeHRMLogin.feature
      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: PIPELINE_TRAINNG_PROJECT/JunitReports/TESTS-*.xml
    
