name: Release_Pipeline_Windows
on:
  push:
    branches:
      - main
  schedule:
      - cron: '40 16 * * *'    
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy: 
        matrix:
          os: [windows-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Chrome version
        run: chrome --version	
      - name: Execute Behave tests Windows
        if: matrix.os=='windows-latest' 
        run: 
          behave .\features\OrgangeHRMLogin.feature
      - name: Execute Behave tests Non Windows
        if: matrix.os=='ubuntu-latest'|| matrix.os== 'macos-latest'
        run: 
          behave ./features/OrgangeHRMLogin.feature    
      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: JunitReports/TESTS-*.xml
    